# Generated by Django 5.1.7 on 2025-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_dish_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
