# Generated by Django 5.1.7 on 2025-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_dish_orderitem_dish_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dish_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
