# Generated by Django 5.1.7 on 2025-03-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_dish_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
