# Generated by Django 5.1.7 on 2025-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('paid', 'Paid')], default='waiting', max_length=20),
        ),
    ]
